site_name: GSB RC Site 2024
site_url: https://rcpedia-dev.stanford.edu
theme:
  name: material
  custom_dir: docs/assets
  features:
    - announce.dismiss
    - header.autohide
    - content.code.annotate
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search
  - blogging
  - git-revision-date-localized

markdown_extensions:
  - codehilite
  - toc
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - admonition
  - pymdownx.details

nav:
  - Home: index.md
  - Getting Started: 
      - Yen Servers: _getting_started/yen-servers.md
      - Access the Yens: _getting_started/how_access_yens.md
      - Jupyter: _getting_started/jupyter.md
      - Modules: _getting_started/modules.md
  - Policies: 
      - User Limits: _policies/user_limits.md
      - Services: _policies/services.md
      - Sherlock: _policies/sherlock.md
      - Collaborators: _policies/collaborators.md
      - Workgroups: _policies/workgroups.md
      - Security: _policies/security.md
      - Human Subjects Research: _policies/humanSubjectsResearch.md
      - Acknowledgements: _policies/acknowledgements.md
      - Leaving GSB: _policies/leavingGSB.md
  - User Guide: 
      - General Practices:
          - Archive: _user_guide/best_practices_archive.md
          - File Management: _user_guide/best_practices_file_management.md
          - Monitor Resource Usage: _user_guide/best_practices_monitor_usage.md
          - GUI: _user_guide/best_practices_gui.md
      - Slurm:
          - Migrating From JupyterHub: _user_guide/best_practices_migrating_from_jupyter.md
          - Julia SLURM Job Arrays: _user_guide/best_practices_julia_jobarray.md
          - R SLURM Job Array: _user_guide/best_practices_R_slurm_job_array.md
          - Python Job Array: _user_guide/best_practices_python_job_array.md
          - Matlab Slurm Job: _user_guide/best_practices_matlab_slurm_job.md
      - Python:
          - Python Virtual Environments: _user_guide/best_practices_python_env.md
          - Parallel Processing Python: _user_guide/best_practices_parallel_processing_python.md
      - R:
          - R: _user_guide/best_practices_r.md
      - Optimization Software:
          - Optimization: _user_guide/best_practices_optimization.md
      - Troubleshooting:
          - Why isn't JupyterHub Working?: _user_guide/best_practices_jupyter_does_not_work.md
          - Man-in-the-Middle Warning: _user_guide/man_in_middle.md
          - Julia on Jupyter: _user_guide/best_practices_julia_jupyter.md
      - Data:
          - Data Transfer: _user_guide/data_transfer.md
  - Tech Blog:
      - SEC Filings: _blog/2023-05-16-EDGARmirror.md
      - Run on GPU: _blog/2024-03-28-run-gpu.md
      - Edit Files on Command Line: _blog/2023-09-20-edit-files-with-vim.md
      - Run Jobs on Yen's GPU Node: _blog/2024-04-25-yen_gpu.md
      - Reproducible Research Essentials: _blog/2024-02-28-reproducibility_tips.md 
      - How do I extract compressed files?: _blog/2023-08-18-how_to_uncompress.md
      - Merging Datasets in Dask: _blog/2023-02-09-merging_data_sets_dask.md
      - How to use Rclone: _blog/2023-09-18-rclone.md
      - Working with Large Zip Files in Python: _blog/2022-10-10_zipfile_guide.md
      - How Do I Install Stata on JupyterHub?: _blog/2022-02-24-install-stata-on-jupyter.md 
      - How Do I Access SEC Documents?: _blog/2021-09-22-how_access_SEC.md 
      - Train BERT model on Yen GPU's: _blog/2024-03-28-finBERT.md 
      - Installing Software on the Yens: _blog/2022-11-14_installing_software.md 
      - Using Twarc Python Package to Scrape Twitter: _blog/2023-08-08-using_twarc.md
      - How do I export my R environment to JupyterHub?: _blog/2023-08-23-howRenvJupyterKernel.md
extra:
  update_date: 2024-08-26

extra_css:
  - assets/css/index.css
  - assets/css/sh.css
  - assets/css/fonts.css
  - css/custom.css
