site_name: GSB RC Site 2024
site_url: https://rcpedia-dev.stanford.edu
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/gsb-logo.png
  features:
    # - announce.dismiss
    - header.autohide
    - content.code.annotate
    - navigation.indexes
    - content.code.select
    - content.code.copy
   # - toc.integrate
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search
  - blog:
      blog_toc: false
  - meta
  - tags:
      listings_toc: false
 
  # CI=1 mkdocs build
  - group:
      enabled: !ENV CI
      plugins:
        - git-revision-date-localized

  # INSIDERS=1 mkdocs build
  - group:
      enabled: !ENV INSIDERS
      plugins:
        - privacy
        - optimize:
            optimize_png: false

markdown_extensions:
  - codehilite
  - toc
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true


nav:
  - Home: index.mdpip install Pygments
  - Getting Started: 
      - Yen Servers: _getting_started/yen-servers.md
      - Access the Yens: _getting_started/how_access_yens.md
      - Jupyter: _getting_started/jupyter.md
      - Modules: _getting_started/modules.md
  - Policies: 
      - User Limits: _policies/user_limits.md
      - Services: _policies/services.md
      - Sherlock: _policies/sherlock.md
      - Collaborators: _policies/collaborators.md
      - Workgroups: _policies/workgroups.md
      - Security: _policies/security.md
      - Human Subjects Research: _policies/humanSubjectsResearch.md
      - Acknowledgements: _policies/acknowledgements.md
      - Leaving GSB: _policies/leavingGSB.md
  - User Guide: 
      - General Practices:
          - Archive: _user_guide/best_practices_archive.md
          - File Management: _user_guide/best_practices_file_management.md
          - Monitor Resource Usage: _user_guide/best_practices_monitor_usage.md
          - GUI: _user_guide/best_practices_gui.md
      - Slurm:
          - Migrating From JupyterHub: _user_guide/best_practices_migrating_from_jupyter.md
          - Julia SLURM Job Arrays: _user_guide/best_practices_julia_jobarray.md
          - R SLURM Job Array: _user_guide/best_practices_R_slurm_job_array.md
          - Python Job Array: _user_guide/best_practices_python_job_array.md
          - Matlab Slurm Job: _user_guide/best_practices_matlab_slurm_job.md
      - Python:
          - Python Virtual Environments: _user_guide/best_practices_python_env.md
          - Parallel Processing Python: _user_guide/best_practices_parallel_processing_python.md
      - R:
          - R: _user_guide/best_practices_r.md
      - Optimization Software:
          - Optimization: _user_guide/best_practices_optimization.md
      - Troubleshooting:
          - Why isn't JupyterHub Working?: _user_guide/best_practices_jupyter_does_not_work.md
          - Man-in-the-Middle Warning: _user_guide/man_in_middle.md
          - Julia on Jupyter: _user_guide/best_practices_julia_jupyter.md
      - Data:
          - Data Transfer: _user_guide/data_transfer.md
  - Blog:
      - blog/index.md
      # - Run Jobs on Yen's GPU Node: blog/posts/2024-04-25-yen_gpu.md
      # - Train BERT model on Yen GPU's: blog/posts/2024-03-28-finBERT.md 
      # - Run on GPU: blog/posts/2024-03-28-run-gpu.md
      # - Reproducible Research Essentials: blog/posts/2024-02-28-reproducibility_tips.md 
      # - Edit Files on Command Line: blog/posts/2023-09-20-edit-files-with-vim.md
      # - How to use Rclone: blog/posts/2023-09-18-rclone.md
      # - How do I export my R environment to JupyterHub?: blog/posts/2023-08-23-howRenvJupyterKernel.md
      # - How do I extract compressed files?: blog/posts/2023-08-18-how_to_uncompress.md
      # - Using Twarc Python Package to Scrape Twitter: blog/posts/2023-08-08-using_twarc.md
      # - SEC Filings: blog/posts/2023-05-16-EDGARmirror.md
      # - Merging Datasets in Dask: blog/posts/2023-02-09-merging_data_sets_dask.md
      # - Installing Software on the Yens: blog/posts/2022-11-14_installing_software.md
      # - Working with Large Zip Files in Python: blog/posts/2022-10-10_zipfile_guide.md
      # - How Do I Access SEC Documents?: blog/posts/2021-09-22-how_access_SEC.md 
      # - How Do I Install Stata on JupyterHub?: blog/posts/2022-02-24-install-stata-on-jupyter.md
      # - What is a man-in-the-middle warning?: blog/posts/2020-03-13-man_in_middle.md


extra:
  update_date: 2024-08-26

extra_css:
  - stylesheets/sh.css
  - stylesheets/output.css # This is the decantur css tailing output
  - stylesheets/custom.css
  - stylesheets/base.css

